# Generated by Django 5.0.4 on 2024-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
